appName: datagen-api
container_name: datagen-api-container

service:
  port: 9080
  targetPort: 8080
  type: LoadBalancer

namespace: dev

deployment:
  replicas: 2

configmap:
  name: datagen-api-configmap
  data:
    CUSTOM_HEADER: "data generator and make it available with FastAPI!"

image:
  name: e4espootin/datagen_api
  tag: latest
