apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-configmap
data:
  API_LOCAL_URL: "http://datagen-api.dev.svc.cluster.local:8080"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-plain.dev.svc.cluster.local:9092"
  ALL_DATASETS: '{"taxitrips":"/taxitrips/?num_samples=1","cobot":"/sensors/cobot?sensor_id=cobot_1001&topic_name=cobot"}'
  MESSAGES_BATCH_SIZE: "100"