apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}
    tier: frontend

